import { localDate } from './domain';
import type { GroupState, Paper } from './types';

export function createDemo(): GroupState {
  const today = localDate();
  const offset = (days: number) => {
    const d = new Date(`${today}T12:00:00`);
    d.setDate(d.getDate() + days);
    return localDate(d);
  };
  const members = [
    'Alex',
    'Maya',
    'Sam',
    'Jordan',
    'Riley',
    'Morgan',
    'Casey',
    'Taylor',
  ].map((name, i) => ({ id: `demo-${i}`, name }));
  const voters = (ids: number[]) => ids.map((id) => members[id].id);
  const paper = (
    id: string,
    title: string,
    authors: string,
    year: string,
    venue: string,
    topic: string,
    url: string,
    ids: number[],
    notes: string,
    days?: number,
    attendance: number[] = [],
  ): Paper => ({
    id,
    title,
    authors,
    year,
    venue,
    topic,
    url,
    notes,
    suggestedBy: members[Number(id.replace('paper-', '')) % members.length].id,
    addedAt: `${offset(-25)}T12:00:00.000Z`,
    date: days === undefined ? '' : offset(days),
    votes: voters(ids),
    attendance: voters(attendance),
  });
  return {
    today,
    members,
    sheetUrl: '',
    papers: [
      paper(
        'paper-1',
        'The Next 700 Programming Languages',
        'Peter J. Landin',
        '1966',
        'Communications of the ACM',
        'Programming languages',
        'https://doi.org/10.1145/365230.365257',
        [0, 1, 2, 3, 4, 5, 6],
        'An old paper with a surprisingly current question: what should a programming language be?',
      ),
      paper(
        'paper-2',
        'Attention Is All You Need',
        'Ashish Vaswani, Noam Shazeer, Niki Parmar et al.',
        '2017',
        'NeurIPS',
        'Machine learning',
        'https://arxiv.org/abs/1706.03762',
        [0, 2, 3, 4, 5],
        'Let’s revisit the architecture behind so much of what we use today.',
      ),
      paper(
        'paper-3',
        'Communicating Sequential Processes',
        'C. A. R. Hoare',
        '1978',
        'Communications of the ACM',
        'Systems',
        'https://doi.org/10.1145/359576.359585',
        [1, 2, 4, 6],
        'A foundation for thinking clearly about concurrency.',
      ),
      paper(
        'paper-4',
        'On the Criteria To Be Used in Decomposing Systems into Modules',
        'David L. Parnas',
        '1972',
        'Communications of the ACM',
        'Software engineering',
        'https://doi.org/10.1145/361598.361623',
        [0, 1, 6],
        'Information hiding, and why the obvious decomposition is not always the best one.',
      ),
      paper(
        'paper-5',
        'A Theory of Type Polymorphism in Programming',
        'Robin Milner',
        '1978',
        'Journal of Computer and System Sciences',
        'Programming languages',
        'https://doi.org/10.1016/0022-0000(78)90014-4',
        [2, 5],
        'How can we get more guarantees while writing fewer annotations?',
      ),
      paper(
        'paper-6',
        'The Bitter Lesson',
        'Richard Sutton',
        '2019',
        'Essay',
        'Machine learning',
        'http://www.incompleteideas.net/IncIdeas/BitterLesson.html',
        [0, 1, 3, 5, 7],
        'A short read, a long discussion. What does this mean for programming tools?',
        4,
      ),
      paper(
        'paper-7',
        'No Silver Bullet — Essence and Accidents of Software Engineering',
        'Frederick P. Brooks, Jr.',
        '1987',
        'Computer',
        'Software engineering',
        'https://doi.org/10.1109/MC.1987.1663532',
        [0, 2, 4],
        '',
        -7,
        [0, 1, 2, 4, 6],
      ),
      paper(
        'paper-8',
        'The UNIX Time-Sharing System',
        'Dennis M. Ritchie, Ken Thompson',
        '1974',
        'Communications of the ACM',
        'Systems',
        'https://doi.org/10.1145/361011.361061',
        [2, 3, 5],
        '',
        -14,
        [0, 1, 3, 5],
      ),
    ],
  };
}
